<bbn-table :source="source.root + 'page/list'"
           :url="source.root + 'actions/task/insert_update'"
           :sortable="true"
           :pageable="true"
           editable="popup"
           :map="addRunning"
           :trClass="(data) => {if ( data.isRunning ){ return 'bbn-bg-red';}}"
           uid="id"
           ref="table"
           :toolbar="[{
             text: _('New task'),
             command: 'insert',
             icon: 'nf nf-fa-plus'
           }]"
>
  <bbns-column field="id"
              :hidden="true"
              :editable="false"
  ></bbns-column>
  <bbns-column field="active"
              :width="90"
              title="<?=_('Active')?>"
              :component="$options.components['appui-cron-switch']"
              :editable="false"
              cls="bbn-c"
  ></bbns-column>
  <bbns-column field="file"
              
              title="<?=_('Controller')?>"
              :render="renderFile"
              :required="true"
              :editor="$options.components['appui-cron-controller']"
  ></bbns-column>
  <bbns-column field="priority"
              :width="50"
              title="<?=_('Prio.')?>"
              ftitle="<?=_('Priority')?>"
              type="number"
              :required="true"
              :default="5"
              :options="{min: 1, max: 5}"
              cls="bbn-c"
  ></bbns-column>
  <bbns-column field="frequency"
              :source="frequencies"
              :hidden="true"
              title="<?=_('Frequency')?>"
              ftitle="<?=_('The time to wait between each execution')?>"
              :required="true"
  ></bbns-column>
  <bbns-column field="timeout"
              :hidden="true"
              title="<?=_('Timeout')?>"
              ftitle="<?=_('Timeout in seconds')?>"
              :required="true"
              type="number"
              :options="{min: 0, max: 86400}"
  ></bbns-column>
  <bbns-column field="prev"
              :width="90"
              title="<?=_('Prev')?>"
              ftitle="<?=_('Date/time of the previous execution')?>"
              type="date"
              format="DD-MM-YYYY HH:mm"
              :editable="false"
              cls="bbn-c"
  ></bbns-column>
  <bbns-column field="next"
              :width="90"
              title="<?=_('Next')?>"
              ftitle="<?=_('Date/time planned for the next execution')?>"
              type="date"
              format="DD-MM-YYYY HH:mm"
              cls="bbn-c"
              :options="{min: currentDate}"
  ></bbns-column>
  <!--bbns-column field="duration"
              :width="60"
              title="<?=_('Dur.')?>"
              ftitle="<?=_('Average duration of the execution')?>"
              :render="renderAvgDuration"
              :editable="false"
              cls="bbn-c"
  ></bbns-column-->
  <bbns-column field="num"
              :width="70"
              type="number"
              title="<?=_('Num')?>"
              ftitle="<?=_('Total number of executions')?>"
              :editable="false"
              cls="bbn-c"
  ></bbns-column>
  <!--bbns-column field="description"
              title="<?=_('Description')?>"
              ftitle="<?=_('Description of the task')?>"
              editor="bbn-rte"
  ></bbns-column-->
  <bbns-column v-if="source.is_dev"
              :width="130"
              ftitle="<?=_('Actions')?>"
              :buttons="renderButtons"
              cls="bbn-c"
  ></bbns-column>
  
</bbn-table>